<a href="https://colab.research.google.com/github/mts-machines-learn/ml-course-dec2019/blob/master/3.%20%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8/002_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Библиотека numpy


## Одномерные массивы

In [0]:
import numpy as np

Инициализация массива:

In [0]:
a = np.array([1, 2, 3])
a, type(a)

(array([1, 2, 3]), numpy.ndarray)

Узнать размерность массива:

In [0]:
a.ndim

1

В $n$-мерном случае возвращается кортеж размеров по каждой координате.

In [0]:
a.shape

(3,)

`size` - это число элементов в массиве

`len` - размер по первой координате

In [0]:
len(a), a.size

(3, 3)

Индексация

In [0]:
a[1]

2

Массивы - изменяемые объекты

In [0]:
a[1] = 10
print(a)

[ 1 10  3]


Массив чисел типа float

In [0]:
b = np.array([1., 2, 3])
b.dtype

dtype('float64')

Указать тип при инициализации

In [0]:
c = np.array([1, 2, 5], dtype=np.float64)
print(c)

[1. 2. 5.]


Приведение типов

In [0]:
print(c.dtype)
print(c.astype(int))
print(c.astype(str))

float64
[1 2 5]
['1.0' '2.0' '5.0']


Массивы, заполненные нулями или единицами

In [0]:
np.zeros(3)


array([0., 0., 0.])

In [0]:
np.ones(3, dtype=np.int64)

array([1, 1, 1])

np.arange

In [0]:
a = np.arange(0, 10, 2)
print(a)

[0 2 4 6 8]


In [0]:
b = np.arange(0., 10, 2)
print(b)

[0. 2. 4. 6. 8.]


## Операции над одномерными массивами

Арифметические операции проводятся поэлементно.

In [0]:
a = np.array([1,2,3,4])
b = np.arange(1,8,2)

In [0]:
print(a + b)

[ 2  5  8 11]


In [0]:
print(a - b)

[ 0 -1 -2 -3]


In [0]:
print(a * b)

[ 1  6 15 28]


In [0]:
print(a / b)

[1.         0.66666667 0.6        0.57142857]


In [0]:
print(a ** 2)

[ 1  4  9 16]


Когда операнды разных типов, они приводятся к большему типу.

In [0]:
print(a + 4.3)

[5.3 6.3 7.3 8.3]


In [0]:
print(a + 1)

[2 3 4 5]


In [0]:
print(2 * a)

[2 4 6 8]


Сравнения

In [0]:
print(a > b)

[False False False False]


In [0]:
print(a == b)

[ True False False False]


In [0]:
c = a > 2
print(c)

[False False  True  True]


Модификация на месте.

In [0]:
a += 1
print(a)

[2 3 4 5]


In [0]:
b *= 2
print(b)

[ 2  6 10 14]


При выполнении операций над массивами деление на 0 не возбуждает исключения, а даёт значения `np.nan` или `np.inf`.

In [0]:
print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))

[  0.  nan  inf -inf]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [0]:
np.nan + 1, np.inf + 1, np.inf * 0, 1. / np.inf

(nan, inf, nan, 0.0)

Сумма и произведение всех элементов массива; максимальный и минимальный элемент; среднее и среднеквадратичное отклонение.

In [0]:
print(b)

[ 2  6 10 14]


In [0]:
b.sum(), b.prod(), b.max(), b.min(), b.mean(), b.std()

(32, 1680, 14, 2, 8.0, 4.47213595499958)

Имеются встроенные функции

In [0]:
print(np.sqrt(b))
print(np.exp(b))
print(np.log(b))
print(np.sin(b))
print(np.e, np.pi)

[1.41421356 2.44948974 3.16227766 3.74165739]
[7.38905610e+00 4.03428793e+02 2.20264658e+04 1.20260428e+06]
[0.69314718 1.79175947 2.30258509 2.63905733]
[ 0.90929743 -0.2794155  -0.54402111  0.99060736]
2.718281828459045 3.141592653589793


Сортировка массива:

In [0]:
b = np.array([1, 4, 2, 3, 5])

In [0]:
print(np.sort(b))
print(b)

[1 2 3 4 5]
[1 4 2 3 5]


In [0]:
b.sort()
print(b)

[1 2 3 4 5]


Конкатенация массивов

In [0]:
print(a)
print(b)

[2 3 4 5]
[1 2 3 4 5]


In [0]:
a = np.hstack((a, b))
print(a)

[2 3 4 5 1 2 3 4 5]


Расщепление массива в позициях 2 и 4.

In [0]:
np.hsplit(a, [2, 4])

[array([2, 3]), array([4, 5]), array([1, 2, 3, 4, 5])]

Функции `delete`, `insert` и `append` не меняют массив на месте, а возвращают новый массив, в котором удалены, вставлены в середину или добавлены в конец какие-то элементы.

In [0]:
a = np.delete(a, [5, 7])
print(a)

[2 3 4 5 1 3 5]


In [0]:
a = np.insert(a, 2, [1000, 1000])
print(a)

[   2    3 1000 1000    4    5    1    3    5]


In [0]:
a = np.append(a, [-1, -2, -3])
print(a)

[   2    3 1000 1000    4    5    1    3    5   -1   -2   -3]


Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.

In [0]:
b = a[2:6]
print(b)

[1000 1000    4    5]


In [0]:
b[0] = -100
print(b)

[-100 1000    4    5]


In [0]:
print(a)

[   2    3 -100 1000    4    5    1    3    5   -1   -2   -3]


Диапазон с шагом 2.

In [0]:
b = a[1:10:2]
print(b)

[   3 1000    5    3   -1]


In [0]:
b[0] = -0.1
print(a)

[   2    0 -100 1000    4    5    1    3    5   -1   -2   -3]


Массив в обратном порядке.

In [0]:
b = a[::-1]
print(b)

[  -3   -2   -1    5    3    1    5    4 1000 -100    0    2]


Подмассиву можно присвоить значение - массив правильного размера или скаляр.

In [0]:
a[1:10:3] = 0
print(a)

[   2    0 -100 1000    0    5    1    0    5   -1   -2   -3]


Тут опять создаётся только новый заголовок, указывающий на те же данные.

In [0]:
b = a[:]
b[1] = 0.1
print(a)

[   2    0 -100 1000    0    5    1    0    5   -1   -2   -3]


In [0]:
b

array([   2,    0, -100, 1000,    0,    5,    1,    0,    5,   -1,   -2,
         -3])

Чтобы скопировать и данные массива, нужно использовать метод `copy`.

In [0]:
b = a.copy()
b[2] = 0
print(b)
print(a)

[   2    0    0 1000    0    5    1    0    5   -1   -2   -3]
[   2    0 -100 1000    0    5    1    0    5   -1   -2   -3]


Можно задать список индексов.

In [0]:
print(a[[2, 3, 5]])

[-100 1000    5]


Можно задать булев массив той же величины.

In [0]:
b = a > 0
print(b)

[ True False False  True False  True  True False  True False False False]


In [0]:
print(a[b])

[   2 1000    5    1    5]


## 2-мерные массивы

In [0]:
a = np.array([[0.0, 1.0], [-1.0, 0.0]])
print(a)

[[ 0.  1.]
 [-1.  0.]]


In [0]:
a.ndim

2

In [0]:
a.shape

(2, 2)

In [0]:
len(a), a.size

(2, 4)

In [0]:
a[1, 0]

-1.0

Арифметические операции поэлементные

In [0]:
print(a)

[[ 0.  1.]
 [-1.  0.]]


In [0]:
b = np.ones((2,2)) * 2
print(b)

[[2. 2.]
 [2. 2.]]


In [0]:
print(a + 1)
print(a * 2)
print(a + [0, 1])  # второе слагаемое дополняется до матрицы копированием строк
print(a + np.array([[0, 2]]).T)  # .T - транспонирование
print(a + b)

[[1. 2.]
 [0. 1.]]
[[ 0.  2.]
 [-2.  0.]]
[[ 0.  2.]
 [-1.  1.]]
[[0. 1.]
 [1. 2.]]
[[2. 3.]
 [1. 2.]]


Поэлементное и матричное умножение.

In [0]:
print(a * b)

[[ 0.  2.]
 [-2.  0.]]


In [0]:
print(b*a)

[[ 0.  2.]
 [-2.  0.]]


In [0]:
print(a @ b)

[[ 2.  2.]
 [-2. -2.]]


In [0]:
print(b @ a)

[[-2.  2.]
 [-2.  2.]]


Умножение матрицы на вектор.

In [0]:
print(b)

[[2. 2.]
 [2. 2.]]


In [0]:
v = np.array([1, 5], dtype=np.float64)
print(b @ v)

[12. 12.]


Единичная матрица.

In [0]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


reshape

In [0]:
print(I.reshape(16))

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [0]:
print(I.reshape(2, 8))

[[1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]]


Строка.

In [0]:
print(I[1])

[0. 1. 0. 0.]


Цикл по строкам.

In [0]:
for row in I:
    print(row)

[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]


Столбец.

In [0]:
print(I[:, 2])

[0. 0. 1. 0.]


Подматрица.

In [0]:
print(I[0:2, 1:3])

[[0. 0.]
 [1. 0.]]


Транспонированная матрица.

In [0]:
print(b.T)

[[2. 2.]
 [2. 2.]]


Соединение матриц по горизонтали и по вертикали.

In [0]:
a = np.array([[0, 1], [2, 3]])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.array([[4, 5], [6, 7], [8, 9]])
print(a)
print(b)
print(c)

[[0 1]
 [2 3]]
[[4 5 6]
 [7 8 9]]
[[4 5]
 [6 7]
 [8 9]]


In [0]:
print(np.hstack((a, b)))

[[0 1 4 5 6]
 [2 3 7 8 9]]


In [0]:
print(np.vstack((a, c)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Сумма всех элементов; суммы столбцов; суммы строк.

In [0]:
print(b)

[[4 5 6]
 [7 8 9]]


In [0]:
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

39
[11 13 15]
[15 24]


Аналогично работают `prod`, `max`, `min` и т.д.

In [0]:
print(b.max())
print(b.max(axis=0))
print(b.max(axis=1))

9
[7 8 9]
[6 9]


След - сумма диагональных элементов.

In [0]:
np.trace(a)

3

## Линейная алгебра

In [0]:
print(a)

[[0 1]
 [2 3]]


In [0]:
np.linalg.det(a)

-2.0

Обратная матрица.

In [0]:
a1 = np.linalg.inv(a)
print(a1)

[[-1.5  0.5]
 [ 1.   0. ]]


In [0]:
print(a @ a1)
print(a1 @ a)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


Решение линейной системы $au=v$.

In [0]:
v = np.array([0, 1], dtype=np.float64)


In [0]:
u = np.linalg.solve(a, v)
print(u)

[0.5 0. ]


Проверим.

In [0]:
print(a @ u - v)

[0. 0.]


In [0]:
print(a1 @ v)

[0.5 0. ]


Собственные значения и собственные векторы: $a u_i = \lambda_i u_i$. `l` - одномерный массив собственных значений $\lambda_i$, столбцы матрицы $u$ - собственные векторы $u_i$.

In [0]:
l, u = np.linalg.eig(a)
print(l)
print(u)

[-0.56155281  3.56155281]
[[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


Проверим.

In [0]:
for i in range(2):
    print(a @ u[:, i] - l[i] * u[:, i])

[0.00000000e+00 1.66533454e-16]
[ 0.0000000e+00 -4.4408921e-16]


Функция `diag` от одномерного массива строит диагональную матрицу; от квадратной матрицы - возвращает одномерный массив её диагональных элементов.

In [0]:
L = np.diag(l)
print(L)
print(np.diag(L))

[[-0.56155281  0.        ]
 [ 0.          3.56155281]]
[-0.56155281  3.56155281]


Все уравнения $a u_i = \lambda_i u_i$ можно собрать в одно матричное уравнение $a u = u \Lambda$, где $\Lambda$ - диагональная матрица с собственными значениями $\lambda_i$ по диагонали.

In [0]:
print(a @ u - u @ L)

[[ 0.00000000e+00  0.00000000e+00]
 [ 1.66533454e-16 -4.44089210e-16]]


Поэтому $u^{-1} a u = \Lambda$.

In [0]:
print(np.linalg.inv(u) @ a @ u)

[[-5.61552813e-01  2.77555756e-17]
 [-2.22044605e-16  3.56155281e+00]]


## Сохранение в файл и чтение из файла

In [0]:
x = np.arange(0, 25, 0.5).reshape((5, 10))

In [0]:
np.save('x.npy', x)

In [0]:
x = np.load('x.npy')
print(x)

[[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5]
 [ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5]
 [15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]
 [20.  20.5 21.  21.5 22.  22.5 23.  23.5 24.  24.5]]
